# Pipeline configuration
url: "https://drive.google.com/file/d/1iPUMC144JCmTf0_wmNhT-7mmAZsNjQvK/view?usp=sharing"
save_archive: "/workspaces/Chatbot-For-Dental-Clinic/Data/Database"
name: "ara_database"
zip_path: "/workspaces/Chatbot-For-Dental-Clinic/Data/arciveData/ara_database.zip"
extract_to: "/workspaces/Chatbot-For-Dental-Clinic/Data/Database"
database_path: "/workspaces/Chatbot-For-Dental-Clinic/Data/Database/ara_database.sqlite"

# Dataframe columns
service_columns:
  - "service_name"
  - "price"
  - "description"
branch_columns:
  - "branch_name"
  - "address"
  - "phone"
  - "working_hours"
social_columns:
  - "platform_name"
  - "link"

# Model configuration
temperature: 0.7
do_sample: true
top_p: 0.9
max_new_tokens: 256
repetition_penalty: 1.1
model_id: "meta-llama/Llama-3.2-1B"
embedding_model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# retrieval configuration
top_k: 5

# Opne AI Model
openai_config_embedding:
  temperature: 0.7
  top_p: 1.0
  max_new_tokens: 150
  do_sample: true
  repetition_penalty: 1.0
  
openai_embedding: "text-embedding-ada-002"  # Specify the embedding model, e.g., OpenAI Ada embedding
openai_model: "gpt-4"  # Specify the LLM model, e.g., GPT-4 or GPT-3.5-turbo
openai: True